oreumi-dreamer/Dreamer

- src/app/api/post/feeds/route.js
- src/components/login/EmailSignup.jsx
- src/components/signup/BasicInfoForm.jsx
- src/components/signup/BasicInfoForm.module.css
주요 변경 사항
1. 피드 로드 API에 자기 자신의 게시글인지 확인하는 isMyself 필드를 추가했습니다.
2. 가입 단계에서 이용 약관 및 개인정보 처리방침 동의 체크박스의 스타일을 수정했습니다.
3. 이메일로 회원 가입 중 '회원가입' 버튼의 레이블 텍스트를 '다음 단계로'로 수정했습니다.
> 피드 API의 isMyself 필드 추가 외

- src/app/api/post/read/[userId]/route.js
- src/components/modal/CommentArticles.jsx
- src/components/modal/PostModal.jsx
- src/components/post/Post.jsx
- src/components/profile/ProfileInfo.jsx
- src/components/write/WritePost.jsx
1. 프로필 API에서 비밀 글 유무를 반환하도록 수정했습니다.
2. 일부 img의 alt 태그 추가 및 일부 텍스트를 적절하게 수정했습니다.
3. 팔로우 및 팔로워 카운트가 실제와 다르게 표시되고 반영되는 문제를 수정했습니다.
> 프로필 API 수정 외 3건

- src/app/globals.css
- src/app/page.module.css
- src/components/Controls.module.css
- src/components/login/SocialLogin.module.css
- src/components/signup/BasicInfoForm.module.css
- src/components/signup/ProfileForm.module.css
- src/components/signup/SignupHeader.module.css
> [Signup page, Login page] dark 모드 색상 적용

- src/app/tomong/Tomong.module.css
- src/app/tomong/page.js
- src/components/header/WideHeader.module.css
- src/components/tomong/TomongListItem.jsx
1. 토몽 페이지에서 게시글 리스트를 컴포넌트로 분리하였습니다.
2. 토몽 게시글 컴포넌트에서 토몽 스탬프를 추가했습니다.
3. 넓은 헤더에서 active됐을 때 레이아웃이 변하는 문제를 수정했습니다.
> 토몽 스탬프 추가 외 1건

- src/components/profile/Profile.jsx
- src/components/write/HashtagModal.jsx
- src/components/write/MoodModal.jsx
- src/components/write/WritePost.jsx
- src/components/write/WritePost.module.css
1. 글작성 모달이 열려 있을 때 배경이 스크롤되는 문제 수정 => html에 `overflow: hidden`
2. 프로필 - 글 쓰러 가기 버튼을 눌러 글작성 모달을 열었을 때
기존: 새로고침
수정: 새로고침되지 않고 모달만 닫히도록 수정
3. label과 input의 for-id가 잘못돼 있던 오타 수정
4. 글작성을 취소한 뒤, 다시 글작성을 할 경우 장르/기분 모달의 선택지가 초기화되지 않음. 해당 문제 수정
> 배경 스크롤/모달 닫을 때 새로고침/오타 수정/오류 수정

- src/components/write/HashtagModal.jsx
- src/components/write/MoodModal.jsx
- src/components/write/WritePost.jsx
1. 글작성 중 내용뿐 아니라 제목, 선택지, 별점 등 변경된 사항이 있으면 경고창 띄우도록 변경
2. 버튼 click 이벤트 변수로 수정
3. 모달을 열 때마다 선택지가 초기화되는 문제 수정
4. 쓰지 않는 코드와 주석 삭제
> 오타 수정, 기능 수정, 주석 삭제

- src/app/globals.css
- src/components/Controls.module.css
- src/components/login/SocialLogin.module.css
> [login page, signup page] dark mode btn style 수정

- src/app/api/post/private/[postId]/route.js
- src/components/main/Post.jsx
- src/components/modal/PostModal.jsx
- src/components/profile/PostList.jsx
- src/components/profile/Profile.jsx
1. 프로필에서 반짝 토글 이후 게시글 클릭 시 상태가 변경되는 문제가 수정되었습니다.
2. 작성자 아이디가 수정되었을 때 이전에 작성한 게시글이 비밀글로 변경되지 않는 문제가 수정되었습니다.
> 반짝 토글 문제 외 4건

- src/components/header/Header.jsx
- src/components/header/NarrowHeader.jsx
- src/components/header/WideHeader.jsx
- src/components/main/Post.jsx
- src/utils/calculateModalPosition.js
프로필 액티브이후 새로고침시 액티브상태 제거되는 버그 수정
WideHeader / NarrowHeader / Post  더보기모달 위치 배치값 수정
> 프로필액티브상태 수정 및 더보기모달위치조정

- src/components/Loading.module.css
- src/components/write/WritePost.jsx
테마가 다크 모드일 때 로드 컴포넌트의 이미지에 필터를 적용하여 흰색으로 보이도록 수정했습니다.
> 로드 컴포넌트의 다크 모드 스타일 추가

- src/components/Loading.jsx
- src/components/main/MainList.jsx
- src/components/main/Post.jsx
- src/components/write/WritePost.module.css
1. 메인 피드에서 반짝을 누르고 게시글을 클릭했을 때 반짝이 풀리는 문제를 수정했습니다.
2. 게시글 작성 모달에서 사용자 프로필 사진의 픽셀 종횡비가 1:1이 아닌 문제를 수정했습니다.
3. 로딩 컴포넌트에서 불필요한 테마 로드 코드를 제거했습니다.
> 반짝을 누르고 게시글을 클릭했을 때 반짝이 풀리는 문제 수정 외 3건

- src/app/api/post/feeds/route.js
- src/components/main/Post.jsx
Algolia 기반의 피드 API를 Firestore에서 직접 참조하도록 수정함에 따라 API와 관련된 코드를 일부 수정했습니다.
> 변경된 API 적용

- src/app/globals.css
- src/components/Controls.jsx
- src/components/login/EmailSignup.jsx
- src/components/login/EmailSignup.module.css
> [Email Signup] 이메일 회원가입 css 적용

- src/app/api/account/avatar/route.js
- src/app/api/account/followers/[userId]/route.js
- src/app/api/post/create/route.js
- src/app/api/post/update/[postId]/route.js
- src/app/reset.css
- src/app/signup/page.js
- src/app/tomong/page.js
- src/components/Controls.jsx
- src/components/Controls.module.css
- src/components/main/MainList.jsx
- src/components/profile/ProfileInfo.jsx
- src/lib/api/avatar.js
1. 사용자 프로필에서 팔로우 및 팔로워 모달 기능을 추가했습니다.
2. PNG를 첨부했을 경우 배경 색이 검정색이 되는 문제를 수정했습니다.
> 팔로우 및 팔로워 모달 적용 및 PNG 배경 색 문제 수정

- src/app/api/post/create/route.js
- src/components/main/Post.jsx
- src/components/post/PostContent.jsx
- src/components/write/WritePost.jsx
1. 삭제된 게시글을 클릭하여 모달로 오픈했을 경우 alert를 띄우고 모달이 닫히도록 수정했습니다.
2. 피드에서 반짝을 눌러도 화면에 반영되지 않는 문제를 수정했습니다.
3. 게시글이 작성되었을 경우 게시글 URL로 리다이렉트되도록 수정했습니다.
> 사용자 경험 개선 및 버그 수정

- src/app/globals.css
- src/components/header/NarrowHeader.jsx
- src/components/header/NarrowHeader.module.css
- src/utils/calculateModalPosition.js
모바일 헤더를 하단으로 옮기고, 스타일이 수정되었습니다.
> 모바일 헤더 스타일 관련 수정

- src/components/Controls.jsx
- src/components/login/EmailSignup.jsx
- src/components/login/EmailSignup.module.css
- src/components/login/SocialLogin.jsx
> 🎨 이메일로 회원가입 validation 적용

- src/components/Controls.module.css
- src/components/login/SocialLogin.module.css
- src/components/signup/BasicInfoForm.module.css
+ 💄 input 태그 autocomplete 적용 시 background, color 브라우저 기본 auto-fill 색상 적용되지 않도록 구현
> 💄 [Email Login, Signup page] dark mode 색상 적용

- src/app/api/auth/check-email/route.js
- src/app/api/auth/verify-email/route.js
- src/app/join/page.js
- src/app/join/page.module.css
- src/app/join/verify-email/page.js
- src/app/signup/page.js
- src/components/auth/AuthStateHandler.jsx
- src/components/login/EmailSignup.jsx
- src/components/login/EmailSignup.module.css
- src/components/login/SocialLogin.jsx
- src/store/authSlice.js
1. 이메일로 회원가입 라우트를 /join으로 별도로 분리했습니다.
2. 회원가입을 진행하지 않으면 영구적으로 로그인이 되지 않는 문제를 수정했습니다.
> ✨ 이메일로 회원가입 페이지 라우트 분리 및 이메일 인증을 받은 이후 회원가입을 진행하지 않으면 영구적으로 로그인이 되지 않는 문제 수정

- src/components/main/MainList.jsx
- src/components/main/Post.jsx
Algolia로 피드 데이터를 불러올 때 사용했던 objectID 변수명을 Firestore의 id로 변경하여 수정했습니다.
> 🐛 피드에서 더 보기 버튼을 클릭한 이후 나오는 게시글이 클릭되지 않는 문제 수정

- src/app/[id]/page.js
- src/app/tomong/page.js
- src/components/header/Header.jsx
- src/components/profile/Profile.jsx
1. 토몽에서 게시글이 0개이거나 해몽된 게시글이 0개일 때 예외 처리를 추가했습니다.
2. 프로필 페이지의 모달과 헤더의 모달이 충돌하여 프로필 페이지에서 글쓰기가 작동하지 않는 문제를 수정했습니다.
> 토몽 예외 처리 및 모달 충돌 수정

- src/app/join/page.module.css
- src/app/page.module.css
- src/app/signup/page.module.css
- src/components/login/SocialLogin.module.css
- src/components/signup/BasicInfoForm.module.css
- src/components/signup/ProfileForm.module.css
- src/components/signup/SignupHeader.jsx
- src/components/signup/SignupHeader.module.css
> [Signup] 모바일 css 적용

- src/app/globals.css
- src/components/Loading.module.css
- src/components/NavProvider.js
- src/components/header/NarrowHeader.module.css
- src/components/main/MainList.module.css
- src/components/main/Post.jsx
- src/components/modal/PostModal.module.css
1. 메인 레이아웃의 커스텀 스크롤 바를 복구했습니다.
2. iOS Safari 환경에서의 사용자 경험을 개선했습니다.
> 반응형 디자인 개선 

- src/app/api/post/read/[userId]/route.js
- src/app/globals.css
1. 다크 모드의 헤더 색상 변수를 추가했습니다.
2. isPrivate 값이 "on"이 반환되는 문제를 수정했습니다.
> 다크 모드 UI 개선 및 isPrivate 버그 수정

- package-lock.json
- package.json
- src/app/api/auth/check-email-verification/route.js
- src/app/api/auth/send-email-verification/route.js
- src/components/Controls.module.css
- src/components/login/EmailSignup.jsx
- src/components/login/EmailSignup.module.css
회원 가입 로직을 이메일 인증 코드 발송 방식으로 변경했고, 스타일을 적용했습니다.
> 회원 가입 로직 변경 및 스타일 수정 

- src/components/Controls.jsx
- src/components/Controls.module.css
1. 커스텀 스크롤 바를 범용적으로 사용할 수 있도록 수정했습니다.
2. 셀렉트 박스에 커스텀 스크롤 바를 적용하고, 네이티브 스크롤 바를 숨김 처리했습니다.
> 커스텀 스크롤 바 수정 및 셀렉트 박스에 커스텀 스크롤 바 적용

- src/app/globals.css
- src/components/footer/Footer.module.css
Footer의 width를 20rem으로 고정하고, 포지션을 absolute로 지정하여 레이아웃 유지보수를 용이화하였습니다.
> Footer 관련 레이아웃 수정

- src/components/Controls.jsx
- src/components/Controls.module.css
- src/components/header/Header.jsx
1. WideHeader 상태에서 프로필 페이지에서 WriteModal을 호출했을 때 게시글 작성이 작동하지 않는 문제를 수정했습니다.
2. 배포 환경에서 체크박스 레이블의 서체 크기가 h2-font-size를 참조하는 문제를 수정했습니다.
3. 커스텀 체크박스의 이미지가 바둑판식으로 표시되는 문제를 수정했습니다.
> WriteModal 버그 수정 외 2건

- src/app/globals.css
- src/app/signup/page.module.css
- src/components/signup/BasicInfoForm.jsx
- src/components/signup/BasicInfoForm.module.css
- src/components/signup/ProfileForm.module.css
Signup 페이지의 반응형 레이아웃, 특히 480px 미만 뷰포트 너비 환경에서의 반응형 레이아웃을 최적화했습니다.
> Signup 페이지 반응형 대응

- src/app/account/Account.module.css
- src/app/account/modify-email/ModifyEmail.module.css
- src/app/account/modify-email/page.js
- src/app/account/modify-password/ModifyPassword.module.css
- src/app/account/modify-password/page.js
- src/app/account/page.js
- src/app/api/auth/check-email/route.js
- src/app/api/auth/update-email/route.js
- src/app/api/auth/withdraw/route.js
- src/app/globals.css
- src/components/Controls.jsx
- src/components/Controls.module.css
- src/components/auth/AuthStateHandler.jsx
- src/components/header/NarrowHeader.module.css
- src/components/profile/Profile.module.css
- src/utils/auth/updateEmail.js
- src/utils/auth/verifyPassword.js
1. 일부 반응형 레이아웃 문제가 수정되었습니다.
2. 계정 설정 페이지 및 이메일 수정, 비밀번호 변경, 회원 탈퇴 기능을 구현했습니다.
> 반응형 레이아웃 수정 및 계정 설정 페이지 구현

- src/components/dropDown/DropDown.jsx
- src/components/main/Post.jsx
- src/components/post/PostContent.jsx
- src/components/profile/PostList.jsx
- src/components/write/HashtagModal.jsx
- src/components/write/MoodModal.jsx
- src/components/write/WritePost.jsx
드롭다운 메뉴에서 게시글 수정 버튼을 눌러 게시글을 수정할 수 있도록 기능을 추가했습니다.
> 게시글 수정 기능 구현

- src/app/api/report/route.js
- src/components/Controls.jsx
- src/components/Controls.module.css
- src/components/dropDown/DropDown.jsx
- src/components/header/HeaderModal.jsx
- src/components/main/Post.jsx
- src/components/post/PostContent.jsx
- src/components/profile/PostList.jsx
- src/components/profile/ProfileEdit.jsx
- src/components/report/Report.jsx
1. 신고 기능이 추가되었습니다. 메인 피드, 본문, 프로필의 드롭다운 메뉴에서 게시글을 신고할 수 있습니다. 중복 신고는 불가합니다.
2. 커스텀 Select의 Options 박스 위치를 조정했습니다.
> 신고 기능 추가 외 1건

- src/app/api/post/feeds/route.js
- src/app/api/post/read/[userId]/route.js
- src/app/api/post/search/[postId]/route.js
API에서 isDeleted를 제외한 댓글의 길이를 로드하도록 수정
> 🐛 commentsCount 필드 값이 실제 댓글 데이터와 차이가 있는 문제 수정

- src/components/header/Header.jsx
- src/components/header/NarrowHeader.jsx
- src/components/header/WideHeader.jsx
- src/components/main/MainList.module.css
- src/components/profile/Profile.module.css
1. url 변경에 따른 WideHeader의 Active 상태가 정상화 되었습니다.
2. 헤더의 "알람" 아이콘이 삭제되었습니다.
3. ProfileEdit 프로필이미지 및 버튼의 레이아웃이 조정되었습니다.
4. main의 Post의 유저 아이디/이름의 길이가 길 때 깨지는 레이아웃이 조정되었습니다.
> 헤더 active조정 +2

- src/app/api/auth/check-email/route.js
- src/app/api/auth/reset-password/route.js
- src/app/join/page.module.css
- src/components/login/FindPassword.jsx
- src/components/login/SocialLogin.jsx
- src/components/login/SocialLogin.module.css
- src/utils/validation.js
비밀번호 찾기 기능 및 관련 API와 컴포넌트가 추가되었습니다.
> 비밀번호 찾기 기능 추가

- src/components/profile/Profile.module.css
> [Profile] 페이지 레이아웃 벗어남 / Footer 겹침 css 수정

- public/robots.txt
- src/app/sitemap.js
- src/components/Controls.jsx
- src/components/header/NarrowHeader.module.css
1. robots.txt와 sitemap.xml을 추가했습니다.
2. 헤더의 알림 버튼 제거에 따른 모바일 footer grid 레이아웃을 수정했습니다.
3. 팔로잉 및 팔로워 모달에서 유저를 클릭하고 페이지가 이동되었을 때 스크롤 방지가 풀리지 않는 문제를 수정했습니다.
> 팔로워 모달 버그 수정 외 2건

- src/app/globals.css
- src/app/signup/page.js
- src/components/Controls.jsx
- src/components/Loading.jsx
- src/components/Loading.module.css
- src/components/dropDown/DropDown.jsx
- src/components/footer/Recommends.jsx
- src/components/header/NarrowHeader.jsx
- src/components/header/WideHeader.module.css
- src/components/main/MainList.jsx
- src/components/main/Post.jsx
- src/components/modal/CommentArticles.jsx
- src/components/modal/PostModal.jsx
- src/components/modal/PostModal.module.css
- src/components/post/PostContent.jsx
- src/components/profile/PostCard.jsx
- src/components/profile/PostList.jsx
- src/components/profile/Profile.module.css
- src/components/profile/ProfileInfo.jsx
- src/components/report/Report.jsx
- src/components/tomong/Tomong.jsx
- src/components/tomong/Tomong.module.css
- src/components/write/WritePost.jsx
- src/utils/scrollHandler.js
일부 환경에서의 반응형 레이아웃을 보완하였고, 접근성이 개선되었습니다.
> 반응형 레이아웃 및 접근성 개선

- src/app/api/post/search/route.js
- src/app/globals.css
- src/app/layout.js
- src/app/page.module.css
- src/app/search/Search.module.css
- src/components/main/Post.jsx
- src/components/modal/PostModal.module.css
- src/components/profile/Profile.module.css
- src/components/write/WritePost.jsx
- src/components/write/WritePost.module.css
1. 전체 레이아웃, PostModal 및 WriteModal의 반응형 레이아웃을 개선했습니다.
2. 검색 API에서 사용자 본인 여부를 반환하는 isMyself 필드를 추가했습니다.
> 반응형 레이아웃 개선 및 검색 버그 수정

- src/app/search/page.js
- src/components/main/MainList.jsx
- src/components/main/Post.jsx
- src/components/modal/CommentArticles.jsx
- src/components/modal/PostModal.jsx
- src/components/modal/PostModal.module.css
- src/components/post/PostContent.jsx
- src/components/profile/Profile.jsx
모달 내에서 댓글 쓰기 혹은 반짝 토글을 할 경우 상위 컴포넌트의 리스트에 반영되도록 수정했습니다.
> 모달에서 게시글 상태 변화 시 상위 컴포넌트의 리스트에 반영되도록 수정

- src/app/api/account/modify/route.js
- src/app/api/auth/update-email/route.js
- src/app/api/comment/create/[postId]/route.js
- src/app/api/comment/delete/[postId]/route.js
- src/app/api/comment/read/[postId]/route.js
- src/app/api/join/check-userid/route.js
- src/app/api/post/feeds/route.js
- src/app/api/post/spark/[postId]/route.js
- src/app/api/post/update/[postId]/route.js
- src/app/api/tomong/streaming-token/route.js
- src/components/main/MainList.module.css
💄 iOS Safari에서 모달을 터치하고 나갔을 때 포커스 아웃라인이 잘리는 문제 수정
> 💄 iOS Safari에서 모달을 터치하고 나갔을 때 포커스 아웃라인이 잘리는 문제 수정

- src/app/globals.css
- src/components/Controls.module.css
- src/components/auth/AuthStateHandler.jsx
- src/components/modal/PostModal.jsx
- src/components/modal/PostModal.module.css
1. 모바일 레이아웃에서 PostModal의 더 보기 버튼의 위치를 수정했습니다.
2. 모달의 padding을 클릭해도 모달이 닫히는 문제를 수정했습니다.
3. 유저 프로필을 비회원 이용자가 접근하지 못하도록 수정했습니다.
> 반응형 레이아웃 수정, 모달 버그 수정 및 유저 프로필 접근 권한 수정

- src/components/modal/PostModal.module.css
> 💄 PostModal의 댓글 입력 레이아웃 조정
